### PR TITLE
refactored: codebase | fixed: TCP GC

### PR DESCRIPTION
**Pull request by ManiMozaffar**
Also made it to be more pythonic friendly,
Please provide me feedback, if required, I'll add testing + workflows.
Github action support 'windows" workflow, so we can actually test if headless is detectable, in linux or windows, or if non-headless is detectable, in linux or windows. Would be nice feature :)

### CODE REVIEW

**Comment by ManiMozaffar** [comment]
@ultrafunkamsterdam

**Comment by ManiMozaffar** [comment]
This didn't  completely fixed bug

I made a test script, so that I can monitor connection leak in a better manner

```
import time
import os

import psutil
import undetected_chromedriver as uc


def check_connections():
    """Check count of ESTABLISHED connections."""
    return len([
        conn for conn in psutil.net_connections()
        if conn.status == 'ESTABLISHED' and conn.pid == os.getpid()
    ])


def main():
    """Main script function."""
    while True:
        driver = uc.Chrome(enable_cdp_events=True)
        driver.get('https://www.google.com')
        driver.quit()
        print(f"Number of established connections: {check_connections()}")
        time.sleep(0.5)


if __name__ == "__main__":
    main()
```


and I found out that listen method in Reactor is causing this, not sure how you can get rid of it, but connection there is opened and listened forevere, I adjusted the code to this, then retired, although it exits from the method just fine, but it actually never closes the port that it was opened, and it remain as "ESTABLISHED"

```

    async def listen(self):
        while self.running:
            await self._wait_service_started()
            await asyncio.sleep(1)

            try:
                acquired = self.lock.acquire(timeout=2)
                if not acquired:
                    continue

                try:
                    log_entries = self.driver.get_log("performance")
                finally:
                    self.lock.release()

                for entry in log_entries:
                    try:
                        obj_serialized: str = entry.get("message")
                        obj = json.loads(obj_serialized)
                        message = obj.get("message")
                        method = message.get("method")

                        if "*" in self.handlers:
                            await self.loop.run_in_executor(
                                None, self.handlers["*"], message
                            )
                        elif method.lower() in self.handlers:
                            await self.loop.run_in_executor(
                                None, self.handlers[method.lower()], message
                            )

                    except Exception as e:
                        raise e from None

            except Exception as e:
                if "invalid session id" in str(e):
                    pass
                else:
                    logging.debug("exception ignored :", e)
```

**Comment by Phil-Peret** [comment]
I try your code, but PipeConnection is not present in multiprocessing

**Comment by ManiMozaffar** [comment]
> I try your code, but PipeConnection is not present in multiprocessing

What do you mean? Have you tried the test script I've written? if you enable TCP, connection leak becomes +=2, everytime you open a browser.
And that's because webdriver is closed, but the listener which was bounded to it was garbage collected afterward, like how it happened before python 3.6 with other objects that were bounded to each other.
We need to defer finalize it.

**Comment by Phil-Peret** [comment]
I mean your pull request, the test code post in this discussion is fine.

**Comment by ManiMozaffar** [comment]
> I mean your pull request, the test code post in this discussion is fine.

Yeah it runs fine, but the problem here is that each time the connection goes += 2. :)
after it reaches 65k, it causes port exhasution.
Running on python v3.9.16, with windows. 
5 different servers, same problem.
I have to kill my process, and run again, so that GC collects them.

**Comment by Phil-Peret** [comment]
Ah okay! I'm sorry, i try your code under linux in python 3.11.  You use multiprocessing in your script? Sometimes is a problem of subprocess in python, it can't close correctly chromedriver & chromium/chorme istance.

**Comment by montovaneli** [comment]
Perhaps this issue is related to it?
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1123

**Comment by ManiMozaffar** [comment]
> Perhaps this issue is related to it? #1123
> 
> When I pulled this commit, I no longer had issues with open connections.

Well somehow, the problem are related to each other, but not same exactly.
here I'm talking about "ESTABLISHED" connections, from cdp. your code doens't involve cdp at all.
as I explained, each time you open/close chrome, it result in leaving 2 ESTABLISHED connection leak, which then increases to 65k allowing all ports to be exhausted and taken, then it'll stop popping up chrome and you can't make any socket connection unless you stop your python process.




> Ah okay! I'm sorry, i try your code under linux in python 3.11. You use multiprocessing in your script? Sometimes is a problem of subprocess in python, it can't close correctly chromedriver & chromium/chorme istance.

This has nothing to do with chromedriver instance directly,
we have a self.driver, which we already quitted. then we call __del__, and it tries to access self.driver to delete the CDP listener bounded to it, but self.driver is already garbage collected and deleted, so it causes in circular references, which needs to be handled.
In python, it handles with an algorithm called Deferred Finalization, but in this case it cannot be used, as the timeline that chromedriver is exited is not same as the time we're removing the listeners.

I have no idea how we can fix this issue. Maybe linux handles this, I don't know how it works there. because in linux you can terminate a socket opened in a process ID, but you can't do that on windows.

**Comment by ManiMozaffar** [comment]
"timeline that chromedriver is exited is not same as the time we're removing the listeners."

had me thinking :D
I told to myself, why chromedriver can't wait  
so I explicitly wait with timeout of 10 seconds, for process to exit, so it can be garbage collected just same as other objects. and boom, it worked out ;)
maybe I have to decrease time waiting cycle, to 0.1secs? idk

**Comment by ManiMozaffar** [comment]
@ultrafunkamsterdam 
so what do I do?
I keep committing here? and you'll merge? to refactor the code completely and create testing workflows?
I have a private repo where I did this, but it's really hard for me to keep up with changes you're doing here.

I have these tests in my mind:
1. Detection test headless ~ cloudflare ~ windows
2. Detection test headful ~ cloudflare ~ windows
3. Detection test headless ~ cloudflare ~ linux
4. Detection test headful ~ cloudflare ~ linux
5-8. same these 4, goes for antoinevastel bot detection test
9-10. headless linux/windows, in creepjs bot detection test
11. Connection leak test


also I believe having a docs, with few readme file, is better practice than making the first main repo's readme very long.

**Comment by bhavul** [comment]
@ManiMozaffar could you tell how we can install your repo until it gets merged?

**Comment by ManiMozaffar** [comment]
> @ManiMozaffar could you tell how we can install your repo until it gets merged?

pip install git+my repo

**Comment by bhavul** [comment]
@ManiMozaffar 

I seem to be getting this error on installing your repo : 
```
File "/Users/abc/Downloads/private-repo/some_bot/some_bot.py", line 10, in <module>
    from _HelloClient import _HelloClient
  File "/Users/abc/Downloads/private-repo/some_bot/_HelloClient.py", line 19, in <module>
    import undetected_chromedriver as uc
  File "/Users/abc/miniconda3/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 36, in <module>
    from .dprocess import start_detached
  File "/Users/abc/miniconda3/lib/python3.10/site-packages/undetected_chromedriver/dprocess.py", line 4, in <module>
    from multiprocessing.connection import PipeConnection
ImportError: cannot import name 'PipeConnection' from 'multiprocessing.connection' (/Users/abc/miniconda3/lib/python3.10/multiprocessing/connection.py)
```

I used this command to install undetected_chromedriver : 

```
pip install git+https://github.com/ManiMozaffar/undetected-chromedriver.git
```

**Pull request closed without merging**
