### PR TITLE
3.0.3 

### PR DESCRIPTION
**Pull request by ultrafunkamsterdam**
v 3.0.3  finally    [  [why 303 is such a good number](https://youtu.be/eWpA_xwT1to?t=60) ]
------------------------------------------------------------------------------------

Hello lovebirds,

- fixed a bug where driver hangs long time on quit
- passing  executable_path explicitly to Chrome() now causes chromedriver to **not** redownload, since some people have issues downloading 3mb but expect to build next-gen scrapers

## some free tips regarding some commonly raised issues: ##

1 - "Wrong version is downloaded, lets download the new chrome and hardcode it in v2.py"
    
    solution:
    
    driver = uc.Chrome(version_main=92)    # or 90, 91, 93
    
    if the file is locked somehow and does not overwrite it:
    
    driver = uc.Chrome(version_main=92, patcher_force_close=True)
    

2 - "look at all those option flags and arguments i copied from some blog, but your chromedriver doesnt work dude"
    example:
    
    options = uc.ChromeOptions() 
    options.headlesss = True      
    options.add_argument('--headless')   # << WRONG. since now chrome starts up using --headless --headless
    
    try to keep it as simple as possible. most of required options are built in
    better yet:  
    
    driver = uc.Chrome(headless=True)    # done
    

              
3 - "Some cloudflare site xyz gives me endless loop help help"
    
     believe me: we know.. really. no need to raise 36 issues regarding some dodgy site using cloudflare.
     
     i know how they do it. that's one step forward.
   
   

4 - "help me i'm trying your driver but does not run on commodore64 or alike - please assist"

    No
  
  

5 - "does this work in C#, C++, --c, Haskell, Java,  Assembly, dos prompt?"

    Probably, if you know how to rewrite it. But i'm not going to do it.
    
    
6 - "I have a question on basic webdriver stuff which are not are not a part of your library but you still need answer me! NOW!"

    NO! 
    look here : https://selenium-python.readthedocs.io/
    or here: https://google.com

### CODE REVIEW

**Comment by ratz-py** [comment]
On UC v2 I'm facing some issues in Proxy support, seems that they are really applied. Any hint?

**Comment by HMaker** [comment]
@ultrafunkamsterdam  Funny joke on commit message haha but avoiding re-download and re-patch for every run is suitable for many cases, for example on containerized webdrivers. Currently I run chromedriver based on alpine linux image in docker containers:
```Dockerfile
RUN apk add chromium chromium-chromedriver
ENV CHROMEDRIVER_PATH /usr/lib/chromium/chromedriver
RUN python -c "from undetected_chromedriver.patcher import Patcher; patcher = Patcher(version_main=86); patcher.executable_path = '$CHROMEDRIVER_PATH'; assert patcher.patch()"
RUN ln -s /usr/bin/chromium-browser /usr/bin/google-chrome
```

**Comment by ultrafunkamsterdam** [comment]
> @ultrafunkamsterdam Funny joke on commit message haha but avoiding re-download and re-patch for every run is suitable for many cases, for example on containerized webdrivers. Currently I run chromedriver based on alpine linux image in docker containers:
> 
> ```dockerfile
> FROM python:3.8.7-alpine3.12
> 
> ENV PYTHONDONTWRITEBYTECODE 1
> ENV PYTHONUNBUFFERED 1
> 
> RUN apk add chromium chromium-chromedriver
> ENV CHROMEDRIVER_PATH /usr/lib/chromium/chromedriver
> RUN python -c "from undetected_chromedriver.patcher import Patcher; patcher = Patcher(version_main=86); patcher.executable_path = '$CHROMEDRIVER_PATH'; assert patcher.patch()"
> RUN ln -s /usr/bin/chromium-browser /usr/bin/google-chrome
> ```

Hi @HMaker ,

Thank you for your comment.

```passing executable_path explicitly to Chrome() now causes chromedriver to not redownload```

please try.

Kind regards,
leon

**Comment by bezkos** [comment]
I dont know if its bug but when u try to add some addition arguments with add_argument finction, u ll see double --headless entry even if u use options.headlesss = True instead of options.add_argument('--headless').

**Comment by sunny9495-dev** [comment]
how to disable chrome password manager, i tried
prefs = {"credentials_enable_service": False,
         "profile.password_manager_enabled": False}
options.add_experimental_option("prefs", prefs)

but it isnt worked.

**Comment by CoderVietAnhLe** [comment]
i cant using multi thread? driver open and can not close , when i using options.user_data_dir = "c:\\temp\\profile"
self.service.process.kill()
AttributeError: 'Chrome' object has no attribute 'service'
how can i fix it? can you give me some example? thank you
And is there any way to install addon in uc? i try but not work, i need it :( , thank youuuuuu

**Comment by sokolov172** [comment]
@ultrafunkamsterdam Hello. I could help you to test data_dome service. if its interesting to you - write me

**Comment by cesarfarhat** [comment]
@ultrafunkamsterdam Hello.  I cant start UC on a virtual display, the driver never starts. If I try with selenium or selenium wire it starts.

**Comment by CoderVietAnhLe** [comment]
Big error, undetected-chromedriver not work when im build to exe. try in Cx_freeze and Py auto exe

**Comment by shahrooz1397** [comment]
please someone tell me how to disable redownloading driver by each run 
i tried both
executable_path=path and browser_executable_path=path
but it still redownloads how to avoid that?

**Comment by shahrooz1397** [comment]
your driver cant open new tab
driver.execute_script('''window.open('');''')
by executing this nothing happens

**Comment by psyhceros** [comment]
I have this error This version of ChromeDriver only supports Chrome version 104 Current browser version is 103.0.5060.134 undetected chrome driver. I just update Chrome to the latest version and it works.

**Comment by krypterro** [comment]
"passing executable_path explicitly to Chrome() now causes chromedriver to not redownload, since some people have issues downloading 3mb but expect to build next-gen scrapers"

We have 16 servers running hundreds of concurrent sessions at a time, and running fresh every 5 minutes, so that 3MB is multiplied by the thousands per hour. We don't particularly care about bandwidth usage, but it would be nice if there was a happy medium between downloading the file every time, and being to set a time limit. For example, it only downloads the file if the file is over 5 minutes old.

**Comment by tmb5cg** [comment]
> "passing executable_path explicitly to Chrome() now causes chromedriver to not redownload, since some people have issues downloading 3mb but expect to build next-gen scrapers"
> 
> 
> 
> We have 16 servers running hundreds of concurrent sessions at a time, and running fresh every 5 minutes, so that 3MB is multiplied by the thousands per hour. We don't particularly care about bandwidth usage, but it would be nice if there was a happy medium between downloading the file every time, and being to set a time limit. For example, it only downloads the file if the file is over 5 minutes old.

Bruv it's open source and free, your frustration is laughable

**Comment by krypterro** [comment]
If you had a donation button somewhere we'd resolve the free part. Just pointing out that some of us are using your code for large scale commercial applications. But of course you are correct on the open source part, I'll be glad to code that up when I get time. Which I rarely do...which is why I mentioned it. Nevertheless, the project is awesome, and we certainly appreciate the hard work that goes into it.

**Comment by ECHO-ECHOOooo** [comment]
I am trying to access a web3 site that requires the metamask extension for logging in to the site.  The standard selenium chromedriver supports an options.add_extension method that can be passed to the driver when it is instantiated.  Your  uc driver seems to ignore the option.  Is there a way to specify this option in the uc driver???

**Comment by KamilMroczek** [comment]
Love these notes bahahahahaha

**Comment by Wizya** [comment]
I get the following error
AttributeError: 'Driver' object has no attribute 'command_executor'

**Pull request merged**
