### PR TITLE
Set a specific data_path for Patcher if the environment is AWS Lambda

### PR DESCRIPTION
**Pull request by AktanKasymaliev**
This PR addresses this issue: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/441

### CODE REVIEW

**Comment by prabhat-banknovo** [comment]
@ultrafunkamsterdam @sebdelsol Please merge this; Will simplify life a lot for running on lambda functions out of the box.

**Comment by DiMiTriFrog** [comment]
Any solve this?

**Comment by juzer-patan** [comment]
Has anyone resolved this issue?

**Comment by ottogutierrez** [comment]
@ultrafunkamsterdam could you please merge this? I would love for this to be included in the library stable version :)

**Comment by ultrafunkamsterdam** [comment]
> @ultrafunkamsterdam could you please merge this? I would love for this to be included in the library stable version :)
Yes I will merge it in the coming update which will be tomorrow or Monday

**Comment by maneendra-zen3** [comment]
I used this. But I am getting this error now. 
```
[ERROR] PermissionError: [Errno 13] Permission denied: '/tmp/undetected_chromedriver'
Traceback (most recent call last):
  File "/var/task/handler.py", line 48, in crawler
    browser = uc.Chrome(options=options)
  File "/opt/python/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 421, in __init__
    browser = subprocess.Popen(
  File "/var/lang/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/var/lang/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
```

**Comment by AktanKasymaliev** [comment]
> I used this. But I am getting this error now.  @AktanKasymaliev. Did you not encounter this error? FYI, I got this error after your code modification. Thanks for that tho :) previous error was resolved
> 
> ```
> 
> [ERROR] PermissionError: [Errno 13] Permission denied: '/tmp/undetected_chromedriver'
> 
> Traceback (most recent call last):
> 
>   File "/var/task/handler.py", line 48, in crawler
> 
>     browser = uc.Chrome(options=options)
> 
>   File "/opt/python/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 421, in __init__
> 
>     browser = subprocess.Popen(
> 
>   File "/var/lang/lib/python3.9/subprocess.py", line 951, in __init__
> 
>     self._execute_child(args, executable, preexec_fn, close_fds,
> 
>   File "/var/lang/lib/python3.9/subprocess.py", line 1821, in _execute_child
> 
>     raise child_exception_type(errno_num, err_msg, err_filename)
> 
> ```
> 
> 
> 
> 

It's probably issues in your path of driver, I wish I helped you but idk

**Pull request merged**
