### PR TITLE
Adding automatic version_main to <Tested on Mac / Win10 / Ubuntu> __init__.py

### PR DESCRIPTION
**Pull request by MattWaller**
Automatically gets version_main from the selected browser_executable, wrapped in Try Except to handle errors which could arise from untested environments. I tested on macos / windows10 / ubuntu 22.04. Works on all from my tests, but in the event that theres an error it will be handled the same way it's currently handled. Also added executable path of brave to linux paths.

### CODE REVIEW

**Comment by sebdelsol** [comment]
That's a great idea because it resolves those recurrent connexion errors when Chrome auto update.
_And there are a bunch of those issues popping up each time it happens_ :)

Maybe you'd rather invoke a shell without `shell=True` which is discouraged when you don't have entire control over its arguments (you don't know where the `executable_path` comes from). So please use `shell=False` with an argument list instead.

By the way on Windows you can even do without an external command.
Unfortunately it adds a dependency on pywin32 and I understand you don't want that.
```python3
from win32api import HIWORD, GetFileVersionInfo

def _chrome_main_version():
    filename = uc.find_chrome_executable()
    info = GetFileVersionInfo(filename, "\\")
    return HIWORD(info["FileVersionMS"])

Chrome(version_main=_chrome_main_version())
```

**Comment by MattWaller** [comment]
That's probably a more stable way of getting the version for windows. But ya, I didn't really want to solve the issue using any external libraries. Executable path is declared on line 333-335
 <code>           options.binary_location = (
                browser_executable_path or find_chrome_executable()
            )</code>

That's why I was piggybacking on-top of the already existing code.

Think the powershell commands would work, but I am unsure if they would work in older versions of windows not sure when powershell added those features. (I know my solution is messy though - defs could be improved, I'm just unsure how. But your idea is good, but I would let Leon decide what would be more appropriate.)

**Comment by sebdelsol** [comment]
You're right, yet `Popen` with `shell=True` [security consideration](https://docs.python.org/3.5/library/subprocess.html#security-considerations) is there since Python `3.5`.
And the earlier version [are not even maintained any more](https://devguide.python.org/versions/#unsupported-versions), so I would consider it safe, because UC actually begins with [**`3.7`**](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/33d2a728488d12936d0bcc1e97f8e7a040a3b31f/setup.py#L57)

**Comment by jdholtz** [comment]
+1 for this. I use undetected_chromedriver in a Docker container and this would fix having to rebuild the image (or exec into a container) to update chrome.

**Comment by ultrafunkamsterdam** [comment]
Good idea! and thanks for this contribution.  invoking powershell (of all...), really? Large part of the userbase is on *nix and apple systems. And yes you have it wrapped around a try except, but that would mean  i need to say to my users (if they not spamming issue tracker anyway..  "yeah sorry this works only on windows").   I have a method here which fetches the version from the binary, but apparently there are slight differences per release, which i still need to tackle. Of course we'd also could just do a walk trough the  folder  where  find_chrome_executable() comes up with. But that also requires steadyness between releases.

**Comment by MattWaller** [comment]
To be honest it was the first solution I found without the need to add dependencies. 
I know 100% there is a better method of obtaining the current chrome version on windows - but I don't have vast expertise on windows devices and don't one windows myself. 
If you have a better method to obtain the windows version that is stable, id use that then. I don't know the best way to query the windows binary and return its version, i was looking for a simple query like "--version", but that doesn't appear to be a solution / a thing on windows.
Only other thing to consider is what @sebdelsol said about the Popen <code>shell=True</code> possible vulnerability.

**Pull request closed without merging**
