### PR TITLE
Fixed close driver issue for Python 3.10+

### PR DESCRIPTION
**Pull request by Raguggg**
Resolved Chrome driver close issue in Python 3.10+

The issue was arising when closing the Chrome driver in Python 3.10 and above, resulting in an 'OSError: [WinError 6] The handle is invalid' error. The problem was traced to a sleep statement in the __init__.py file, which has been temporarily addressed by commenting out the time.sleep(0.1) line.

This pull request proposes the temporary fix as mentioned, with the aim of resolving the handle invalid error. Further investigation and refinement may be needed to find a more robust solution.

Please review and consider merging these changes. Thank you.

### CODE REVIEW

**Comment by jdholtz** [comment]
This fix is already in a few PRs, most notably #1339

**Comment by Raguggg** [comment]
image
In you latest code it not updated we face issues in our windows server and when we comment time.sleep(0.1) it works

**Comment by syx1031** [comment]
Does this issue fixed? I also get this problem in Python3.11, Windows OS!

**Comment by syx1031** [comment]
I got this problem raised by try-except, I know that it doesn't influence functions, but it looks ugly...

**Pull request closed without merging**
